repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude_types: [json, binary]
  - repo: https://github.com/psf/black
    rev: "23.9.1"
    hooks:
      - id: black-jupyter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.0.292"
    hooks:
      - id: ruff
        exclude: "^docs/"
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/kynan/nbstripout
    rev: "0.6.1"
    hooks:
      - id: nbstripout
  # - repo: https://github.com/RobertCraigie/pyright-python
  #   rev: v1.1.324
  #   hooks:
  #     - id: pyright
  #       additional_dependencies:
  #         - nox
  #         - pytest
  #         - jax
  #         - equinox
  #         - jpu>=0.0.2
