repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude_types: [json, binary]
  - repo: https://github.com/psf/black
    rev: "23.1.0"
    hooks:
      - id: black-jupyter
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.254"
    hooks:
      - id: ruff
        exclude: "^docs/"
        args: [--fix, --exit-non-zero-on-fix]
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v1.0.0"
  #   hooks:
  #     - id: mypy
  #       exclude: "^docs/"
