name: Tests

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  merge_group:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9", "3.10", "3.11"]
        session:
          - "test"
        include:
          - os: "ubuntu-latest"
            python-version: "3.11"
            session: "test_x64"
          - os: "macos-latest"
            python-version: "3.11"
            session: "test"
          - os: "ubuntu-latest"
            python-version: "3.9"
            session: "comparison"

    steps:
      - name: "Init: checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: "Init: Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install: dependencies"
        run: |
          python -m pip install -U pip
          python -m pip install -U nox

      - name: "Tests: run"
        run: |
          python -m nox --non-interactive --error-on-missing-interpreter \
            --session "${{matrix.session}}-${{matrix.python-version}}"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U build twine
      - name: Build the distribution
        run: python -m build .
      - name: Check the distribution
        run: python -m twine check --strict dist/*
      - uses: actions/upload-artifact@v3
        with:
          path: dist/*

  publish:
    environment:
      name: pypi
      url: https://pypi.org/p/jaxoplanet
    permissions:
      id-token: write
    needs: [tests, build]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@v1.8.10
